GitLab1
brstu/MMIPU-2021 pull request #9
Opened 2021-09-30 20:27 UTC by AlexKulikovskiy

2021-10-01 09:39 UTC, idzm requested changes
Доработать файл отчета - добавить форматирование, которое обычно использовалось при оформлении отчета в **MS Word** (*.doc).
Удалить из запроса лишние файлы.

2021-10-03 16:50 UTC, AlexKulikovskiy reviewed
Removed unnecessary files

2021-10-03 18:48 UTC, AlexKulikovskiy reviewed
[README.md](https://github.com/brstu/MMIPU-2021/files/7274354/README.md)

2021-10-04 06:59 UTC, idzm requested changes
Разместить файлы в корректном каталоге - `trunk\as00xxyy`.

2021-10-04 07:20 UTC, AlexKulikovskiy reviewed
Change

2021-10-04 08:00 UTC, idzm approved these changes

2021-10-04 08:01 UTC, merged